### ISSUE TITLE
acgateway - Crash after SBC Update

### ISSUE THREAD

**Issue by uffsalot** [HeinleinSupport/check_mk_extensions#164] opened 2024-08-02 06:13 UTC
Hi,

we've recently updated our audiocodes gateway to version 7.40A.251.150 and discovered that the SIP performance check crashes with a indexError (list index out of range)

Traceback:
`  File "/omd/sites/cmk1/lib/python3/cmk/base/agent_based/checking/_checking.py", line 416, in get_aggregated_result
    consume_check_results(
  File "/omd/sites/cmk1/lib/python3/cmk/base/api/agent_based/checking_classes.py", line 484, in consume_check_results
    for subr in subresults:
  File "/omd/sites/cmk1/lib/python3/cmk/base/api/agent_based/register/check_plugins.py", line 93, in filtered_generator
    for element in generator(*args, **kwargs):
  File "/omd/sites/cmk1/local/lib/python3/cmk/base/plugins/agent_based/acgateway_sipperf.py", line 96, in check_acgateway_sipperf
    for key, value in enumerate(section[0][0]):`

Local Variables:
`{'section': [[], []],
 'sipperf_info': {0: ('sip_calls_attempted',
                      'Number of Attempted SIP/H323 calls'),
                  1: ('sip_calls_established',
                      'Number of established (connected and voice activated) '
                      'SIP/H323 calls'),
                  2: ('sip_destination_busy',
                      'Number of Destination Busy SIP/H323 calls'),
                  3: ('sip_no_answer', 'Number of No Answer SIP/H323 calls'),
                  4: ('sip_no_route',
                      'Number of No Route SIP/H323 calls. Most likely to be '
                      'due to wrong number'),
                  5: ('sip_no_capability',
                      'Number of No capability match between peers on SIP/H323 '
                      'calls'),
                  6: ('sip_failed', 'Number of failed SIP/H323 calls'),
                  7: ('sip_fax_attempted',
                      'Number of Attempted SIP/H323 fax calls'),
                  8: ('sip_fax_success',
                      'Number of SIP/H323 fax success calls'),
                  9: ('sip_total_duration',
                      'total duration of SIP/H323 calls')},
 'this_time': 1722578922.716995,
 'vs': <cmk.base.api.agent_based.value_store._utils._ValueStore object at 0x7fed60d5f590>}`

Checkmk Version: 2.2.0p27
Audiocodes Firmware: 7.40A.251.150

if you need more information, hit me up. Also open for debugging (preferably in german)

**Comment by gurubert** [comment] 2024-08-20 12:06
Please send me the SNMP-Walk of the device. You can get it via the action menu of the "Check_MK" service.

**Comment by uffsalot** [comment] 2024-09-23 08:24
I've started a snmpwalk bevor my vacation (end of august) and it is still running. 16GB and ongoing. This can't be right?

**Comment by gurubert** [comment] 2024-09-23 09:59
No, this cannot be correct. Please talk to the vendor of the device.

**Comment by philippeduthoit** [comment] 2024-10-24 11:13
same issue here, it looks like an endless loop :-(
Shall I perform a numeric walk ?

**Comment by gurubert** [comment] 2024-10-28 08:44
I would need the result of `cmk --snmpwalk HOSTNAME` from the device. The resulting file can be found in `$OMD_ROOT/var/check_mk/snmpwalks/HOSTNAME`.

**Comment by philippeduthoit** [comment] 2024-10-28 11:50
We need to upgrade our appliance, I think uffsalot has the same issue
The issue is resolved in 7.40A.501.384

![image](https://github.com/user-attachments/assets/0e952e44-fed5-452a-8163-e1536381d127)

https://www.audiocodes.com/media/h3yfqroz/sbc-gateway-release-notes-for-long-term-support-lts-versions-740a500.pdf

**Comment by uffsalot** [comment] 2024-10-28 14:27
Good find! 
I will check with our telephony team which version we are using and whether an update is possible.

**Comment by uffsalot** [comment] 2024-11-13 09:57
We are currently running 7.40A.501.392 and SNMPWALK is working again!
I have sent you the SNMP walk via e-mail to the address in your Github profile @gurubert .

**Comment by gurubert** [comment] 2024-11-22 15:16
Fixed with commit acc0ff5b3b70a6a7764f0207a63af23a1a297429

The SNMP agent in the new firmware does not have the necessary OIDs any more.
The discovery function did not test properly, hence the crash.

This has been fixed, the service "SIP Performance" will not be discovered any more.

**Closed as completed by gurubert** 2024-11-22 15:16 UTC
